[package]
name = "learn_rust_by_test"
version = "0.1.0"
authors = ["Jeff Li <lijinfeng01@inspur.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
